[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = odoo_db
db_port = 5432
db_user = odoo
db_password = odoo123
db_name = odoo
admin_passwd = admin123
http_port = 8069
logfile = /var/log/odoo/odoo.log
log_level = warn
