"""
run_briefing.py - Monday Morning CEO Briefing generator (Silver Tier).

Reads the vault state (Needs_Action, Done, Logs) and writes a structured
Plan_CEOBriefing_<date>.md to Plans/General/.

Usage:
    python3 scripts/run_briefing.py

Typically triggered by cron at 8AM on weekdays.
"""

import sys
from pathlib import Path
from datetime import datetime, timedelta

sys.path.insert(0, str(Path(__file__).parent))
from base_watcher import setup_logging

PROJECT_ROOT = Path(__file__).parent.parent
VAULT        = PROJECT_ROOT / "AI_Employee_Vault"

logger = setup_logging(VAULT, "Briefing")


def count_files(folder: Path, pattern: str = "*.md") -> int:
    if not folder.exists():
        return 0
    return len(list(folder.glob(pattern)))


def read_recent_log_lines(n: int = 30) -> list[str]:
    log = VAULT / "Logs" / "activity.log"
    if not log.exists():
        return []
    lines = log.read_text(encoding="utf-8").splitlines()
    return lines[-n:]


def summarize_needs_action() -> list[str]:
    folder = VAULT / "Needs_Action"
    if not folder.exists():
        return []
    items = []
    for f in sorted(folder.glob("*.md")):
        # Read first line of frontmatter for type/urgency
        try:
            lines = f.read_text(encoding="utf-8").splitlines()
            urgency = next((l.split(": ")[1] for l in lines if l.startswith("urgency:")), "Normal")
            type_  = next((l.split(": ")[1] for l in lines if l.startswith("type:")), "unknown")
            emoji  = {"Critical": "🔴", "High": "🟡", "Normal": "🟢"}.get(urgency, "⚪")
            items.append(f"- {emoji} `{f.name}` ({type_}, {urgency})")
        except Exception:
            items.append(f"- ⚪ `{f.name}`")
    return items


def summarize_done_this_week() -> list[str]:
    folder = VAULT / "Done"
    if not folder.exists():
        return []
    cutoff = datetime.now() - timedelta(days=7)
    items = []
    for f in sorted(folder.glob("*.md")):
        if datetime.fromtimestamp(f.stat().st_mtime) >= cutoff:
            items.append(f"- [x] `{f.name}`")
    return items


def summarize_approvals() -> list[str]:
    folder = VAULT / "Pending_Approval"
    if not folder.exists():
        return []
    items = []
    for f in folder.glob("*.md"):
        items.append(f"- ⏳ `{f.name}` — awaiting your decision")
    return items


def generate_briefing() -> Path:
    now   = datetime.now()
    date  = now.strftime("%Y-%m-%d")
    dname = now.strftime("%A, %B %-d, %Y")

    pending_items   = summarize_needs_action()
    done_items      = summarize_done_this_week()
    approval_items  = summarize_approvals()
    recent_logs     = read_recent_log_lines(20)

    pending_count  = count_files(VAULT / "Needs_Action")
    done_count     = count_files(VAULT / "Done")
    approved_count = count_files(VAULT / "Approved")

    pending_block  = "\n".join(pending_items)  if pending_items  else "- ✅ Nothing pending!"
    done_block     = "\n".join(done_items)     if done_items     else "- *(no items completed this week)*"
    approval_block = "\n".join(approval_items) if approval_items else "- ✅ No approvals waiting"
    log_block      = "\n".join(f"  {l}" for l in recent_logs) if recent_logs else "  *(no recent activity)*"

    briefing = f"""---
type: ceo_briefing
generated: {now.isoformat()}
period: last 7 days
status: active
---

# Monday Morning CEO Briefing
### {dname}

---

## Executive Summary

| Metric | Count |
|--------|-------|
| Pending items | {pending_count} |
| Completed this week | {len(done_items)} |
| Awaiting your approval | {len(approval_items)} |
| Items in Done/ total | {done_count} |

---

## Pending Items (Needs_Action/)

{pending_block}

---

## Completed This Week (Done/)

{done_block}

---

## Approvals Waiting for You

{approval_block}

> To approve: move the file to `Approved/`
> To reject: move to `Rejected/` or delete

---

## Recent Activity Log

```
{log_block}
```

---

## Priorities for This Week

- [ ] Review all 🔴 Critical items first
- [ ] Process any 🟡 High urgency emails
- [ ] Review pending approvals
- [ ] Check LinkedIn for new messages/leads
- [ ] Run Gmail watcher if not already scheduled

---

## Proactive Suggestions

- [ ] If inbox has grown — consider increasing watcher check_interval
- [ ] If Done/ has >50 files — archive older items to free space
- [ ] Post a LinkedIn update this week to stay visible (run `linkedin-post` skill)

---

*Generated by AI Employee — Silver Tier · {now.strftime("%Y-%m-%d %H:%M")}*
"""

    out_dir = VAULT / "Plans" / "General"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"Plan_CEOBriefing_{date}.md"
    out_path.write_text(briefing, encoding="utf-8")
    return out_path


def main():
    logger.info("Generating Monday Morning CEO Briefing...")
    path = generate_briefing()
    logger.info(f"Briefing written to: {path.relative_to(PROJECT_ROOT)}")
    print(f"\nBriefing ready: {path}")


if __name__ == "__main__":
    main()
